### ISSUE TITLE
Incorrect Report for United Airlines Tab Behavior

### ISSUE THREAD

**Issue by scottaohara** [a11yrocks/issues#5]
The [United airlines weird tab behaviour](https://issues.a11y.rocks/report/2018-01-20-united-airlines-weird-tab-behaviour) is odd, but not inaccessible.

The Flight, Hotel and Car options are all part of a tab interface.  Using a screen reader will announce them as such, and using arrow keys will navigate and auto load the associated tab panel.

If anything, the issue here is that there is no visual difference to indicate to sighted keyboard users that these controls will behave differently than the "cruise" and "vacation" links that look no different than the tabs.

**Comment by AgtLucas** [comment]
@scottaohara Thanks, that's true! Can you please open a PR?

Thank you!

**Comment by diessica** [comment]
We've improved the report based on your feedback.

https://issues.a11y.rocks/report/2018-01-20-united-airlines-weird-tab-behaviour

Thank you!
